import { useCallback, useEffect, useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import './ui.css'

type Context={sessionId:string;workdir:string;projectId?:string}
type Dirty={clean:boolean;modified:number;files:string[];porcelain:string}
type Remote={name:string;fetchUrl:string;pushUrl:string}
type Branch={name:string;sha?:string;upstream?:string|null;current?:boolean}
type Repo={isRepository:boolean;cwd:string;toplevel?:string|null;commonDir?:string|null;branch?:string|null;headSha?:string|null;upstream?:string|null;ahead?:number;behind?:number;dirty?:Dirty;remotes?:Remote[];branches?:Branch[]}
type Workspace={name:string;path?:string;branch?:string}
type Session={id:string;title?:string;workspace?:string|null;branch?:string|null;isRunning?:boolean}
type Snapshot={context:Context;repo:Repo|null;branches:Branch[];workspaces:Workspace[];sessions:Session[];error?:string}

const PLUGIN_ID='openfox-git-workspace-map'
const TOKEN=new URLSearchParams(location.search).get('token')??''
export async function rpc<T>(method:string,params:Record<string,unknown>={}):Promise<T>{
  const url=new URL(`/api/plugins/${encodeURIComponent(PLUGIN_ID)}/rpc/${encodeURIComponent(method)}`,location.origin);if(TOKEN)url.searchParams.set('token',TOKEN)
  const response=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({params})});const body=await response.json().catch(()=>({})) as {result?:T;error?:string};if(!response.ok)throw new Error(body.error||`RPC ${method} failed (${response.status})`);return body.result as T
}
export async function loadSnapshot():Promise<Snapshot>{
  const context=await rpc<Context>('resolveContext');const observed=await rpc<{ok:boolean;repo?:Repo;error?:string}>('observe');const repo=observed.ok?observed.repo??null:null
  if(!context.sessionId)return{context,repo,branches:repo?.branches??[],workspaces:[],sessions:[],error:observed.error}
  const [br,ws,sess]=await Promise.all([rpc<{branches?:Branch[]}>('listBranches').catch(()=>({branches:[]})),rpc<{workspaces?:Workspace[]}>('listWorkspaces').catch(()=>({workspaces:[]})),rpc<{sessions?:Session[]}>('listSessions').catch(()=>({sessions:[]}))])
  return{context,repo,branches:br.branches??repo?.branches??[],workspaces:ws.workspaces??[],sessions:sess.sessions??[],error:observed.error}
}

export function App(){
 const[s,setS]=useState<Snapshot|null>(null),[loading,setLoading]=useState(false),[toast,setToast]=useState<string>(''),[branch,setBranch]=useState(''),[source,setSource]=useState(''),[wsName,setWsName]=useState(''),[wsBranch,setWsBranch]=useState(''),[wsSource,setWsSource]=useState(''),[remote,setRemote]=useState('')
 const refresh=useCallback(async()=>{setLoading(true);try{setS(await loadSnapshot())}catch(e){setToast(e instanceof Error?e.message:String(e))}finally{setLoading(false)}},[])
 useEffect(()=>{void refresh();const id=setInterval(()=>void refresh(),15000);return()=>clearInterval(id)},[refresh])
 const run=useCallback(async(label:string,fn:()=>Promise<unknown>)=>{setLoading(true);try{await fn();setToast(label);await refresh()}catch(e){setToast(e instanceof Error?e.message:String(e))}finally{setLoading(false)}},[refresh])
 const repo=s?.repo,dirty=repo?.dirty
 const sessionCounts=useMemo(()=>{const m=new Map<string,number>();for(const x of s?.sessions??[])if(x.workspace)m.set(x.workspace,(m.get(x.workspace)??0)+1);return m},[s?.sessions])
 async function removeWorkspace(w:Workspace){if(!confirm(`Delete workspace “${w.name}”?`))return;setLoading(true);try{const r=await rpc<{retryWithForce?:boolean;conflictingSessionIds?:string[]}>('deleteWorkspace',{target:w.name,force:false});if(r?.retryWithForce){const ids=r.conflictingSessionIds?.join(', ')||'other sessions';if(!confirm(`Workspace is used by ${ids}. Force delete?`))return;await rpc('deleteWorkspace',{target:w.name,force:true})}setToast(`Deleted ${w.name}`);await refresh()}catch(e){setToast(e instanceof Error?e.message:String(e))}finally{setLoading(false)}}
 const upstreamRemote=repo?.upstream?.split('/')[0],origin=repo?.remotes?.find(r=>r.name===upstreamRemote)
 return <main className="app"><header><div><h1>Git Workspace Map</h1><p>{s?.context.sessionId?`session ${s.context.sessionId.slice(0,8)}`:s?.context.workdir||'No context'}</p></div><div className="row"><button disabled={loading} onClick={()=>void refresh()}>Refresh</button><button disabled={loading} onClick={()=>void run('Fetched all remotes',()=>rpc('fetch'))}>Fetch all + prune</button></div></header>
 <section className="grid"><article><h2>Topology</h2>{!repo?<p className="muted">Loading…</p>:!repo.isRepository?<p className="muted">Not a Git repository.</p>:<div className="topology">{[['Upstream',repo.commonDir||repo.toplevel],['Workspace',repo.toplevel||repo.cwd],['Branch',repo.branch?`${repo.branch} @ ${repo.headSha}`:`detached @ ${repo.headSha}`],...(repo.upstream?[['Tracking',repo.upstream],['Origin',origin?`${origin.name} (${origin.fetchUrl})`:upstreamRemote]]:[])].map(([k,v],i)=><div key={k}>{i>0&&<div className="arrow">↓</div>}<div className="node"><small>{k}</small><strong>{v||'—'}</strong></div></div>)}</div>}</article>
 <article><h2>Status</h2><dl><dt>Branch</dt><dd>{repo?.branch||'—'}</dd><dt>HEAD</dt><dd className="mono">{repo?.headSha||'—'}</dd><dt>Upstream</dt><dd>{repo?.upstream||'—'}</dd><dt>Ahead / behind</dt><dd>↑{repo?.ahead??0} ↓{repo?.behind??0}</dd><dt>Working tree</dt><dd>{dirty?.clean?'clean':`${dirty?.modified??0} modified`}</dd></dl>{dirty&&!dirty.clean&&<ul className="files">{dirty.files.map(f=><li key={f}>{f}</li>)}</ul>}</article></section>
 <article><h2>Branches</h2><div className="form"><input aria-label="New branch" value={branch} onChange={e=>setBranch(e.target.value)} placeholder="feat/my-change"/><input aria-label="Source branch" value={source} onChange={e=>setSource(e.target.value)} placeholder="source (optional)"/><button disabled={loading||!branch.trim()} onClick={()=>void run(`Created ${branch}`,async()=>{await rpc('createBranch',{name:branch.trim(),...(source.trim()?{sourceBranch:source.trim()}:{})});setBranch('');setSource('')})}>Create & checkout</button></div><div className="list">{(s?.branches??[]).map(b=><div className="item" key={b.name}><div><strong>{b.current?'★ ':''}{b.name}</strong><small>{b.upstream||'no upstream'}</small></div><button disabled={loading||b.current} onClick={()=>void run(`Checked out ${b.name}`,()=>rpc('checkoutBranch',{branch:b.name}))}>Checkout</button></div>)}</div></article>
 <article><h2>Workspaces</h2><div className="form four"><input aria-label="Workspace name" value={wsName} onChange={e=>setWsName(e.target.value)} placeholder="issue-123"/><input aria-label="Workspace branch" value={wsBranch} onChange={e=>setWsBranch(e.target.value)} placeholder="branch (optional)"/><input aria-label="Workspace source" value={wsSource} onChange={e=>setWsSource(e.target.value)} placeholder="source (optional)"/><button disabled={loading||!wsName.trim()} onClick={()=>void run(`Workspace ${wsName} ready`,async()=>{await rpc('createWorkspace',{target:wsName.trim(),...(wsBranch.trim()?{branch:wsBranch.trim()}:{}),...(wsSource.trim()?{sourceBranch:wsSource.trim()}:{})});setWsName('');setWsBranch('');setWsSource('')})}>Create / switch</button></div><div className="list"><div className="item"><div><strong>original</strong><small>main project workspace</small></div><button onClick={()=>void run('Switched to original',()=>rpc('switchWorkspace',{target:'original'}))}>Switch</button></div>{(s?.workspaces??[]).map(w=><div className="item" key={w.name}><div><strong>{w.name}</strong><small>{w.path||w.branch||''}{sessionCounts.get(w.name)?` · ${sessionCounts.get(w.name)} session(s)`:''}</small></div><div className="row"><button onClick={()=>void run(`Switched to ${w.name}`,()=>rpc('switchWorkspace',{target:w.name}))}>Switch</button><button className="danger" onClick={()=>void removeWorkspace(w)}>Delete</button></div></div>)}</div></article>
 <section className="grid"><article><h2>Remotes</h2><div className="form two"><select aria-label="Remote" value={remote} onChange={e=>setRemote(e.target.value)}><option value="">all remotes</option>{(repo?.remotes??[]).map(r=><option key={r.name}>{r.name}</option>)}</select><button onClick={()=>void run(remote?`Fetched ${remote}`:'Fetched all remotes',()=>rpc('fetch',remote?{remote}:{}))}>Fetch</button></div><div className="list">{(repo?.remotes??[]).map(r=><div className="item" key={r.name}><div><strong>{r.name}</strong><small className="mono">{r.fetchUrl}{r.pushUrl&&r.pushUrl!==r.fetchUrl?` · push ${r.pushUrl}`:''}</small></div></div>)}</div></article><article><h2>Project sessions</h2><div className="list">{(s?.sessions??[]).slice(0,25).map(x=><div className="item" key={x.id}><div><strong>{x.title||x.id.slice(0,8)}</strong><small>{[x.workspace||'original',x.branch].filter(Boolean).join(' · ')}</small></div>{x.isRunning&&<span className="pill">running</span>}</div>)}</div></article></section>
 {toast&&<div role="status" className="toast">{toast}</div>}</main>
}

if(document.getElementById('root'))createRoot(document.getElementById('root')!).render(<App/>)
